name: Publish to NuGet

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+(-test)?"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore PdfGate.sln

      - name: Build
        run: dotnet build PdfGate.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test PdfGate.sln --configuration Release --no-build

      - name: Pack
        run: dotnet pack src/PdfGate.net/PdfGate.net.csproj --configuration Release --no-build --output artifacts

      - name: NuGetTest login (OIDC)
        if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-test')
        id: login-test
        uses: NuGet/login@v1
        with:
          user: ${{ secrets.NUGET_USER }}
          audience: https://int.nugettest.org

      - name: NuGet login (OIDC)
        if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-test')
        id: login
        uses: NuGet/login@v1
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push package to NuGetTest.org
        if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-test')
        run: dotnet nuget push "artifacts/*.nupkg" --api-key "${{ steps.login-test.outputs.NUGET_API_KEY }}" --source "https://apiint.nugettest.org/v3/index.json" --skip-duplicate

      - name: Push package to NuGet.org
        if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-test')
        run: dotnet nuget push "artifacts/*.nupkg" --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
